CHUNK_SYMBOL = '@'
LOGIC_PARAM_SYMBOL = '?'
LOGIC_NEGATIVE_SYMBOL = '!'

CREATOR_IGNORE_FILE = '.creator-ignore'
CREATOR_SCRIPT_FILE = '.creator-script'

CREATOR_SCRIPT_STAGE_VARIABLE = 'CREATOR_SCRIPT_STAGE'
CREATOR_SCRIPT_ITEM_VARIABLE = 'CREATOR_SCRIPT_ITEM'

CREATOR_SCRIPT_STAGE_BEFORE = 'BEFORE'
CREATOR_SCRIPT_STAGE_AFTER = 'AFTER'

CREATOR_SCRIPT_ITEM_ROOT = '/'

DEFAULT_IGNORED_FILES = [
    '.git',
    '.DS_Store',
    CREATOR_IGNORE_FILE,
    CREATOR_SCRIPT_FILE,
]
